# Site settings
name: 刘一帆的IT日志
email: liu1fan@gmail.com
author: 刘一帆
url: http://liu1fan.github.io
resume_site: #http://www.hifreud.com/Resume.io/
github: https://github.com/liu1fan/
baseurl: ""
description: Actually, less is more!
meta_description: 刘一帆;个人博客;
motto: It's our wits that make us men.
banner: Stay Hungry, Stay Foolish.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liu1fan
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : liu1fan
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light